/*
 * Maze_Game
 * game which will make you happy
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.57
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.MazeGame);
  }
}(this, function(expect, MazeGame) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new MazeGame.UsersApi();
  });

  describe('(package)', function() {
    describe('UsersApi', function() {
      describe('userGet', function() {
        it('should call userGet successfully', function(done) {
          // TODO: uncomment, update parameter values for userGet call and complete the assertions
          /*

          instance.userGet(name, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MazeGame.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('userPost', function() {
        it('should call userPost successfully', function(done) {
          // TODO: uncomment, update parameter values for userPost call and complete the assertions
          /*

          instance.userPost(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(MazeGame.InlineResponse200);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
