openapi: 3.0.0
info:
  title: Maze_Game
  contact: {}
  description: game which will make you happy
  version: 0.1.0
servers:
  - url: http://localhost:3000
paths:
  /user:
    get:
      parameters:
      - in: query
        name: name
        required: true
        schema:
          type: string
      tags:
        - Users
      description: gets userId by userName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    minimum: 1
                  name: 
                    type: string
                  online: 
                    type: boolean
    post:
      tags:
        - Users
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      description: creates user
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id: 
                    type: integer
                    minimum: 1
                  name: 
                    type: string
                  online: 
                    type: boolean